plugins:
  - '@dotcom-tool-kit/mocha'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/circleci'
  - '@dotcom-tool-kit/npm'
  - '@dotcom-tool-kit/circleci-npm'
commands:
  test:local:
    - Eslint
    - Mocha
  test:ci:
    - Eslint
    - Mocha
options:
  plugins:
    '@dotcom-tool-kit/circleci':
      nodeVersion: 18.16-browsers
  tasks:
    Eslint:
      files: 
        - '**/*.{js,yml,json}'
    Prettier:
      files:
        - '**/*.{js,yml,json}'
    Mocha:
      configPath: '.mocharc.json'
      files: ''
